### ISSUE TITLE
Updated for New Variable Names and Element Selectors for State and Credit Card Expiration Month and Year

### ISSUE THREAD

**Issue by liam-ot** [Quantzz/supremeBot#2]
The previous version worked when the variable names and element types corresponded. Since then Supreme has updated it's params and I have touched up the code. Another change made is that Supreme automatically updates city, state, and country based on zip code, which means you don't have to worry about filling in those sections, you need only add in zip code and rest is auto filled, saving you possibly crucial milliseconds. Also they have changed params for CVV and Card Number to very odd names, they are denoted with a comment in the checkoutFunc().
Happy Shopping! (: 

`"""
Created on Fri Nov  1 13:54:14 2019

@author: BitcoinBoy
"""
import requests
import bs4 as bs
from splinter import Browser
import helpers
from time import sleep

class supremeBot(object):
    def __init__(self, **info):
        self.base_url = 'http://www.supremenewyork.com/'
        self.shop = 'shop/all/'
        self.checkout = 'checkout/'
        self.info = info

    def initializeBrowser(self):
        driver = self.info["driver"]
        path = helpers.get_driver_path(driver)
        if driver == "geckodriver":
            self.b = Browser()
        elif driver == "chromedriver":
            executable_path = {"executable_path": path}
            self.b = Browser('chrome', **executable_path)

    def findProduct(self):
        try:
            r = requests.get(
                "{}{}{}".format(
                    self.base_url,
                    self.shop,
                    self.info['data-category'])).text
            soup = bs.BeautifulSoup(r, 'lxml')

            temp_tuple = []
            temp_link = []

            for link in soup.find_all('a', href=True):
                temp_tuple.append((link['href'], link.text))
            for i in temp_tuple:
                if i[1] == self.info['product-name'] or i[1] == self.info['product-style']:
                    temp_link.append(i[0])

            self.final_link = list(
                set([x for x in temp_link if temp_link.count(x) == 2]))[0]
            return True
        except:
            return False

    def visitSite(self):
        self.b.visit(
            "{}{}".format(
                self.base_url, str(
                    self.final_link)))
        self.b.find_option_by_text(self.info['size']).click()
        self.b.find_by_value('add to cart').click()
        #sleep for 1 sec to ward off crashes caused by browser lag
        sleep(0.5)
    
    
    def checkoutFunc(self):

        self.b.visit("{}{}".format(self.base_url, self.checkout))
        
        self.b.fill("order[billing_name]", self.info['namefield'])
        self.b.fill("order[email]", self.info['emailfield'])
        self.b.fill("order[tel]", self.info['phonefield'])

        self.b.fill("order[billing_address]", self.info['addressfield'])
        self.b.fill("order[billing_zip]", self.info['zip'])
        

        #CC number named riearmxa
        self.b.fill("riearmxa", self.info['card_number'])
        self.b.select("credit_card[month]", self.info['month'])
        self.b.select("credit_card[year]", self.info['year'])
        #CC ccv named credit_card[meknk]
        self.b.fill("credit_card[meknk]", self.info['ccv'])
        self.b.find_by_css('.terms').click()
        self.b.find_by_value("process payment").click()

if __name__ == "__main__":
    INFO = {
        "driver": "geckodriver",
        "product-name": "Supreme®/Schott® Fringe Suede Coat",
        "product-style": "Red",
        "size": "Medium",
        "data-category": "Jackets",
        "namefield": "First Last",
        "emailfield": "email@gmail.com",
        "phonefield": "12345678901",
        "addressfield": "Nowhere St.",
        "zip": "12345",
        "card_number": "1234123412341234",
        "month": "04",
        "year": "2023",
        "ccv": "000"
    }
    BOT = supremeBot(**INFO)
    # Flag to set to true if you want to reload the page continously close to drop.
    found_product = False
    max_iter = 10
    counter = 1
    while not found_product and counter < max_iter:
        found_product = BOT.findProduct()
        print("Tried ", counter, " times")
        counter += 1
    if not found_product:
        raise Exception("Couldn't find product. Sry bruh")
    BOT.initializeBrowser()
    BOT.visitSite()
    BOT.checkoutFunc()`

**Comment by Francisco919** [comment]
Hello, would you be able to attach a downloadable .py file? I have indented code where ever required yet I am still having issues running the code. For some reason it is telling me supremeBot() takes no arguments. Thanks!
